### ISSUE TITLE
RTNETLIN answers: Permission denied; exited with code 1

### ISSUE THREAD

**Issue by Demon-tk** [monstrenyatko/docker-openvpn-client#2]
Good afternoon,

I am unable to start the image. Upon issuing the command `sudo docker-compose up` I receive the error `openvpn-client exited with code 1`.

I have attached a log file on gist: https://gist.github.com/Demon-tk/c6d840328d1ac0989ee723ab50ac04be

It seems that the primary error occurs after `/sbin/ip -6 addr add fde6:7a:7d20:e14::1024/64 dev tun0` is issued, which gives the error `RTNETLINK answers: Permission denied`.

**Comment by Demon-tk** [comment]
I think this might be a temporary workaround
```yml
sysctls:
  - net.ipv6.conf.all.disable_ipv6=0
  ````

Found from this post #issue-530129248

**Comment by monstrenyatko** [comment]
Hi @Demon-tk, looks like it is the Docker issue and your solution is an acceptable workaround. I see similar proposition on the Docker forum, see [link](https://forums.docker.com/t/unable-to-add-ipv6-address-to-dummy-interface-inside-the-container/83321)
